name: Npm Publish

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/npm-publish.yml
  workflow_dispatch:

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-publish.yml@main
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
