name: Npm Publish

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/npm-publish.yml
  workflow_dispatch:

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-publish.yml@npm-publish-1.1.0
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    with:
      generate-documentation-command: "npx typedoc --out ./docs --entryPointStrategy expand ./*.tsx"
