name: NPM Publish

on:
  push:
    branches:
      - 'main'
    paths:
      - 'package.json'

      
jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-publish.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
